// Generated by theming/generate.py from theming/palette.json.
pragma Singleton
import Quickshell
import QtQuick
import Quickshell.Io

Singleton {
  FileView {
    path: Quickshell.shellDir + "/config/colors.json"
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {
      id: palette

      property color bg0: "#19191f"
      property color bg1: "#1f1f26"
      property color bg2: "#292930"
      property color bg3: "#33333c"
      property color bg4: "#42424d"
      property color fg: "#e7e2e3"
      property color red: "#f17070"
      property color orange: "#faa365"
      property color yellow: "#f5d983"
      property color green: "#94e997"
      property color mint: "#9ff8a5"
      property color aqua: "#89edd7"
      property color blue: "#81b7fd"
      property color purple: "#bb92e9"
      property color gray0: "#68666c"
      property color gray1: "#7f7680"
      property color gray2: "#958595"
    }
  }

  readonly property color bg0: palette.bg0
  readonly property color bg1: palette.bg1
  readonly property color bg2: palette.bg2
  readonly property color bg3: palette.bg3
  readonly property color bg4: palette.bg4
  readonly property color fg: palette.fg
  readonly property color red: palette.red
  readonly property color orange: palette.orange
  readonly property color yellow: palette.yellow
  readonly property color green: palette.green
  readonly property color mint: palette.mint
  readonly property color aqua: palette.aqua
  readonly property color blue: palette.blue
  readonly property color purple: palette.purple
  readonly property color gray0: palette.gray0
  readonly property color gray1: palette.gray1
  readonly property color gray2: palette.gray2

  readonly property color accent: purple

  function tint(c) {
    return Qt.alpha(c, 0.18)
  }
}
