-- Wisteria Dusk
-- Generated by theming/generate.py from theming/palette.json.
-- Edit those, not this file.

hl.config({
  general = {
    col = {
      active_border         = { colors = { "rgba(bb92e9ff)", "rgba(81b7fdff)" }, angle = 45 },
      inactive_border       = "rgba(33333cab)",
      nogroup_border        = "rgba(33333cab)",
      nogroup_border_active = "rgba(faa365ff)",
    },
  },

  decoration = {
    shadow = {
      color          = "rgba(131318ed)",
      color_inactive = "rgba(13131899)",
    },
  },

  group = {
    col = {
      border_active          = { colors = { "rgba(89edd7ff)", "rgba(81b7fdff)" }, angle = 45 },
      border_inactive        = "rgba(33333cab)",
      border_locked_active   = { colors = { "rgba(ea89a1ff)", "rgba(faa365ff)" }, angle = 45 },
      border_locked_inactive = "rgba(33333cab)",
    },
    groupbar = {
      text_color          = "rgba(1f1f26ff)",
      text_color_inactive = "rgba(e7e2e3ff)",
      col = {
        active          = "rgba(89edd7ff)",
        inactive        = "rgba(42424dff)",
        locked_active   = "rgba(ea89a1ff)",
        locked_inactive = "rgba(42424dff)",
      },
    },
  },

  misc = {
    background_color = "rgba(131318ff)",
  },
})
