# Wisteria Dusk
# Generated by theming/generate.py from theming/themes/wisteria-dusk.json.
# Edit those, not this file.

PROMPT="%(?:%F{#9ff8a5}%B%1{➜%}%b:%F{#f17070}%B%1{➜%}%b)%f %F{#bb92e9}%B%c%b%f"
PROMPT+=' $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%F{#958595}%1{%} "
ZSH_THEME_GIT_PROMPT_SUFFIX="%f "
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{#faa365}%1{✗%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""
