
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:

require("settings")

require("modules.monitors")
require("modules.autostarts")
require("modules.env")
require("modules.permissions")
require("modules.decorations")
require("modules.colors")
require("modules.animations")
require("modules.layouts")
require("modules.inputs")
require("modules.keybinds")
require("modules.misc")
require("modules.rules")
require("modules.launcher")
require("modules.roles")

