-- Wisteria Dusk lualine theme
-- Generated by theming/generate.py from theming/themes/wisteria-dusk.json.
-- Edit those, not this file.
-- lualine's "auto" theme loads this whenever the colorscheme is wisteria_dusk.
return {
  normal = {
    a = { bg = "#bb92e9", fg = "#19191f", gui = "bold" },
    b = { bg = "#292930", fg = "#bb92e9" },
    c = { bg = "#19191f", fg = "#e7e2e3" },
  },
  insert = {
    a = { bg = "#9ff8a5", fg = "#19191f", gui = "bold" },
    b = { bg = "#292930", fg = "#9ff8a5" },
    c = { bg = "#19191f", fg = "#e7e2e3" },
  },
  terminal = {
    a = { bg = "#9ff8a5", fg = "#19191f", gui = "bold" },
    b = { bg = "#292930", fg = "#9ff8a5" },
    c = { bg = "#19191f", fg = "#e7e2e3" },
  },
  command = {
    a = { bg = "#faa365", fg = "#19191f", gui = "bold" },
    b = { bg = "#292930", fg = "#faa365" },
    c = { bg = "#19191f", fg = "#e7e2e3" },
  },
  visual = {
    a = { bg = "#81b7fd", fg = "#19191f", gui = "bold" },
    b = { bg = "#292930", fg = "#81b7fd" },
    c = { bg = "#19191f", fg = "#e7e2e3" },
  },
  replace = {
    a = { bg = "#f17070", fg = "#19191f", gui = "bold" },
    b = { bg = "#292930", fg = "#f17070" },
    c = { bg = "#19191f", fg = "#e7e2e3" },
  },
  inactive = {
    a = { bg = "#19191f", fg = "#bb92e9" },
    b = { bg = "#19191f", fg = "#42424d", gui = "bold" },
    c = { bg = "#19191f", fg = "#68666c" },
  },
}
