shell zsh
shell_integration disabled
confirm_os_window_close 0
enable_audio_bell no

font_family JetBrainsMono Nerd Font
font_size 18

cursor_shape block
cursor_blink_interval 0
cursor_trail 1

background_opacity 0.80

remember_window_size no
initial_window_width 78c
initial_window_height 23c
window_padding_width 24

scrollbar_track_opacity 0

sync_to_monitor no
repaint_delay 8
input_delay 3

