"""btop theme. Keys follow btop's built-in Default theme; each *_start/_mid/_end
triple is a gradient from low to high values."""

OUT = "btop/.config/btop/themes/{slug}.theme"


def build(c):
    def ramp(start, mid, end):
        return {"start": start, "mid": mid, "end": end}

    keys = {
        # Empty means the terminal's own background, which keeps Ghostty's
        # background-opacity; any color here would paint over it
        "main_bg": "",
        "main_fg": c.text,
        "title": c.text,
        "hi_fg": c.accent,
        "selected_bg": c.surface1,
        "selected_fg": c.bright,
        "inactive_fg": c.overlay0,
        "graph_text": c.subtext0,
        "meter_bg": c.surface1,
        "proc_misc": c.property,
        "cpu_box": c.overlay0,
        "mem_box": c.overlay0,
        "net_box": c.overlay0,
        "proc_box": c.overlay0,
        "div_line": c.surface2,
    }
    gradients = {
        "temp": ramp(c.success, c.warning, c.error),
        "cpu": ramp(c.secondary, c.accent, c.hue.pink),
        "free": ramp(c.hue.teal, c.hue.green, c.hue.green),
        "cached": ramp(c.label, c.hue.blue, c.hue.blue),
        "available": ramp(c.module, c.hue.yellow, c.hue.yellow),
        "used": ramp(c.hue.orange, c.parameter, c.hue.red),
        "download": ramp(c.label, c.hue.blue, c.property),
        "upload": ramp(c.parameter, c.hue.pink, c.identifier),
        "process": ramp(c.property, c.accent, c.hue.pink),
    }
    for name, stops in gradients.items():
        keys.update({f"{name}_{stop}": color for stop, color in stops.items()})

    lines = [
        f"# {c.name}",
        f"# Generated by theming/generate.py from {c.source}.",
        "# Edit those, not this file.",
        "",
        *(f'theme[{key}]="{value}"' for key, value in keys.items()),
    ]
    return {OUT.format(slug=c.slug): "\n".join(lines) + "\n"}
