"""btop theme. Keys follow btop's built-in Default theme; each *_start/_mid/_end
triple is a gradient from low to high values."""

OUT = "btop/.config/btop/themes/wisteria-dusk.theme"


def build(c):
    def ramp(start, mid, end):
        return {"start": start, "mid": mid, "end": end}

    keys = {
        # Empty means the terminal's own background, which keeps Ghostty's
        # background-opacity; any color here would paint over it
        "main_bg": "",
        "main_fg": c.text,
        "title": c.text,
        "hi_fg": c.lavender,
        "selected_bg": c.surface1,
        "selected_fg": c.bright,
        "inactive_fg": c.overlay0,
        "graph_text": c.subtext0,
        "meter_bg": c.surface1,
        "proc_misc": c.lilac,
        "cpu_box": c.overlay0,
        "mem_box": c.overlay0,
        "net_box": c.overlay0,
        "proc_box": c.overlay0,
        "div_line": c.surface2,
    }
    gradients = {
        "temp": ramp(c.green, c.yellow, c.red),
        "cpu": ramp(c.blue, c.lavender, c.pink),
        "free": ramp(c.teal, c.green, c.green),
        "cached": ramp(c.sapphire, c.blue, c.blue),
        "available": ramp(c.ochre, c.yellow, c.yellow),
        "used": ramp(c.peach, c.maroon, c.red),
        "download": ramp(c.sapphire, c.blue, c.lilac),
        "upload": ramp(c.maroon, c.pink, c.flamingo),
        "process": ramp(c.lilac, c.lavender, c.pink),
    }
    for name, stops in gradients.items():
        keys.update({f"{name}_{stop}": color for stop, color in stops.items()})

    lines = [
        f"# {c.name}",
        "# Generated by theming/generate.py from theming/palette.json.",
        "# Edit those, not this file.",
        "",
        *(f'theme[{key}]="{value}"' for key, value in keys.items()),
    ]
    return {OUT: "\n".join(lines) + "\n"}
