"""Ghostty theme: terminal background, cursor, selection and the 16 ANSI colors."""

OUT = "ghostty/.config/ghostty/themes/Wisteria Dusk"


def build(c):
    lines = [
        f"# {c.name}",
        "# Generated by theming/generate.py from theming/palette.json.",
        "# Edit those, not this file.",
        "",
        "# terminal.background in palette.json. Black reads as a neutral tint",
        "# over the wallpaper with background-opacity in the ghostty config.",
        f"background = {c.terminal_background}",
        f"foreground = {c.text}",
        "",
        f"cursor-color = {c.mint}",
        f"cursor-text = {c.base}",
        "",
        f"selection-background = {c.surface2}",
        f"selection-foreground = {c.text}",
        "",
        f"split-divider-color = {c.surface1}",
        "",
        "# ANSI normal colors (black is lifted off the background so it stays visible)",
        *(f"palette = {i}={c.ansi[i]}" for i in range(8)),
        "",
        "# ANSI bright colors",
        *(f"palette = {i}={c.ansi[i]}" for i in range(8, 16)),
    ]
    return {OUT: "\n".join(lines) + "\n"}
