"""GTK 3 and GTK 4 user stylesheets that recolor adw-gtk3 and libadwaita.

Both read libadwaita's named colors: adw-gtk3 (GTK 3) through @define-color,
libadwaita 1.6+ (GTK 4) through CSS variables on :root. The GTK 4 file sets
both so plain GTK 4 apps on the adw-gtk3 theme pick it up too."""

OUT3 = "gtk/.config/gtk-3.0/gtk.css"
OUT4 = "gtk/.config/gtk-4.0/gtk.css"


def build(c):
    colors = {
        "accent_color": c.accent,
        "accent_bg_color": c.accent,
        "accent_fg_color": c.crust,
        "destructive_color": c.error,
        "destructive_bg_color": c.error,
        "destructive_fg_color": c.crust,
        "success_color": c.marker,
        "success_bg_color": c.success,
        "success_fg_color": c.crust,
        "warning_color": c.warning,
        "warning_bg_color": c.warning,
        "warning_fg_color": c.crust,
        "error_color": c.error,
        "error_bg_color": c.error,
        "error_fg_color": c.crust,
        "window_bg_color": c.base,
        "window_fg_color": c.text,
        "view_bg_color": c.mantle,
        "view_fg_color": c.text,
        "headerbar_bg_color": c.surface0,
        "headerbar_fg_color": c.text,
        "headerbar_backdrop_color": c.base,
        "headerbar_border_color": c.surface1,
        "sidebar_bg_color": c.surface0,
        "sidebar_fg_color": c.text,
        "sidebar_backdrop_color": c.base,
        "sidebar_border_color": c.surface1,
        "secondary_sidebar_bg_color": c.base,
        "secondary_sidebar_fg_color": c.text,
        "secondary_sidebar_backdrop_color": c.base,
        "secondary_sidebar_border_color": c.surface1,
        "card_bg_color": c.surface0,
        "card_fg_color": c.text,
        "dialog_bg_color": c.surface0,
        "dialog_fg_color": c.text,
        "popover_bg_color": c.surface1,
        "popover_fg_color": c.text,
        "thumbnail_bg_color": c.surface1,
        "thumbnail_fg_color": c.text,
    }

    header = [
        f"/* {c.name}",
        f" * Generated by theming/generate.py from {c.source}.",
        " * Edit those, not this file. */",
        "",
    ]
    defines = [f"@define-color {name} {value};" for name, value in colors.items()]
    variables = [
        ":root {",
        *(f"  --{name.replace('_', '-')}: {value};" for name, value in colors.items()),
        "}",
    ]
    return {
        OUT3: "\n".join(header + defines) + "\n",
        OUT4: "\n".join(header + defines + [""] + variables) + "\n",
    }
