"""Hyprland colors: modules/colors.lua, an hl.config() call that sets only the
color options (borders, shadow, groups). Sizes, rounding and the rest stay in
modules/decorations.lua."""
from palette import alpha

OUT = "hyprland/.config/hypr/modules/colors.lua"

# Angle of the active border gradient, in degrees
BORDER_ANGLE = 45


def build(c):
    def rgba(color, amount=1.0):
        return f'"rgba({alpha(color, amount)[1:]})"'

    def gradient(*colors):
        return f"{{ colors = {{ {', '.join(rgba(x) for x in colors)} }}, angle = {BORDER_ANGLE} }}"

    content = f"""-- {c.name}
-- Generated by theming/generate.py from theming/palette.json.
-- Edit those, not this file.

hl.config({{
  general = {{
    col = {{
      active_border         = {gradient(c.lavender, c.blue)},
      inactive_border       = {rgba(c.surface1, 0.67)},
      nogroup_border        = {rgba(c.surface1, 0.67)},
      nogroup_border_active = {rgba(c.peach)},
    }},
  }},

  decoration = {{
    shadow = {{
      color          = {rgba(c.crust, 0.93)},
      color_inactive = {rgba(c.crust, 0.6)},
    }},
  }},

  group = {{
    col = {{
      border_active          = {gradient(c.teal, c.blue)},
      border_inactive        = {rgba(c.surface1, 0.67)},
      border_locked_active   = {gradient(c.maroon, c.peach)},
      border_locked_inactive = {rgba(c.surface1, 0.67)},
    }},
    groupbar = {{
      text_color          = {rgba(c.base)},
      text_color_inactive = {rgba(c.text)},
      col = {{
        active          = {rgba(c.teal)},
        inactive        = {rgba(c.surface2)},
        locked_active   = {rgba(c.maroon)},
        locked_inactive = {rgba(c.surface2)},
      }},
    }},
  }},

  misc = {{
    background_color = {rgba(c.crust)},
  }},
}})
"""
    return {OUT: content}
