"""KDE color scheme. KDE apps (Dolphin, Kate, Okular) read some colors through
KColorScheme from kdeglobals instead of the Qt palette qt6ct sets, so they need
this too. Sections and keys follow /usr/share/color-schemes/BreezeDark.colors;
the backgrounds match the qtct and gtk targets."""
from palette import blend

OUT = "kde/.local/share/color-schemes/{pascal}.colors"


def build(c):
    def rgb(color):
        return ",".join(str(int(color[i:i + 2], 16)) for i in (1, 3, 5))

    foregrounds = {
        "DecorationFocus": c.accent,
        "DecorationHover": c.accent,
        "ForegroundActive": c.accent,
        "ForegroundInactive": c.subtext0,
        "ForegroundLink": c.link,
        "ForegroundNegative": c.error,
        "ForegroundNeutral": c.hue.orange,
        "ForegroundNormal": c.text,
        "ForegroundPositive": c.success,
        "ForegroundVisited": c.visited,
    }

    def colors(normal, alternate, **overrides):
        return {"BackgroundAlternate": alternate, "BackgroundNormal": normal,
                **foregrounds, **overrides}

    # Text on the lavender selection has to be dark, so its foregrounds differ
    selection = colors(
        c.accent, blend(c.accent, 0.45, c.base),
        ForegroundActive=c.crust,
        ForegroundInactive=c.surface2,
        ForegroundLink=c.mantle,
        ForegroundNegative=c.urgent,
        ForegroundNeutral=c.crust,
        ForegroundNormal=c.crust,
        ForegroundPositive=c.crust,
        ForegroundVisited=c.mantle,
    )

    sections = {
        "ColorEffects:Disabled": {
            "Color": rgb(c.surface0),
            "ColorAmount": "0",
            "ColorEffect": "0",
            "ContrastAmount": "0.65",
            "ContrastEffect": "1",
            "IntensityAmount": "0.1",
            "IntensityEffect": "2",
        },
        "ColorEffects:Inactive": {
            "ChangeSelectionColor": "true",
            "Color": rgb(c.overlay0),
            "ColorAmount": "0.025",
            "ColorEffect": "2",
            "ContrastAmount": "0.1",
            "ContrastEffect": "2",
            "Enable": "false",
            "IntensityAmount": "0",
            "IntensityEffect": "0",
        },
        "Colors:Button": colors(c.surface0, c.surface1),
        "Colors:Complementary": colors(c.crust, c.mantle),
        "Colors:Header": colors(c.surface0, c.base),
        "Colors:Header][Inactive": colors(c.base, c.surface0),
        "Colors:Selection": selection,
        "Colors:Tooltip": colors(c.surface0, c.base),
        "Colors:View": colors(c.mantle, c.base),
        "Colors:Window": colors(c.base, c.surface0),
        "General": {
            "ColorScheme": c.pascal,
            "Name": c.name,
            "shadeSortColumn": "true",
        },
        "KDE": {"contrast": "4"},
        "WM": {
            "activeBackground": c.surface0,
            "activeBlend": c.text,
            "activeForeground": c.text,
            "inactiveBackground": c.base,
            "inactiveBlend": c.subtext0,
            "inactiveForeground": c.subtext0,
        },
    }

    lines = [
        f"# {c.name}",
        f"# Generated by theming/generate.py from {c.source}.",
        "# Edit those, not this file.",
    ]
    for section, keys in sections.items():
        lines += ["", f"[{section}]"]
        lines += [f"{key}={rgb(v) if v.startswith('#') else v}" for key, v in keys.items()]
    return {OUT.format(pascal=c.pascal): "\n".join(lines) + "\n"}
