"""qt6ct color scheme: one QPalette per color group, selected in qt6ct's
Appearance tab. Each line lists colors in QPalette::ColorRole order."""

OUT = "qt6ct/.config/qt6ct/colors/wisteria-dusk.conf"

# QPalette::ColorRole order. Accent was added in Qt 6.6; the schemes shipped
# with qt6ct stop at PlaceholderText.
ROLES = [
    "WindowText", "Button", "Light", "Midlight", "Dark", "Mid", "Text",
    "BrightText", "ButtonText", "Base", "Window", "Shadow", "Highlight",
    "HighlightedText", "Link", "LinkVisited", "AlternateBase", "NoRole",
    "ToolTipBase", "ToolTipText", "PlaceholderText", "Accent",
]


def build(c):
    active = {
        "WindowText": c.text,
        "Button": c.surface0,
        "Light": c.surface2,
        "Midlight": c.surface1,
        "Dark": c.crust,
        "Mid": c.mantle,
        "Text": c.text,
        "BrightText": c.bright,
        "ButtonText": c.text,
        "Base": c.mantle,
        "Window": c.base,
        "Shadow": c.crust,
        "Highlight": c.lavender,
        "HighlightedText": c.crust,
        "Link": c.blue,
        "LinkVisited": c.lavender,
        "AlternateBase": c.base,
        "NoRole": c.base,
        "ToolTipBase": c.surface0,
        "ToolTipText": c.text,
        "PlaceholderText": c.overlay0,
        "Accent": c.lavender,
    }
    disabled = {
        **active,
        "WindowText": c.overlay0,
        "Text": c.overlay0,
        "ButtonText": c.overlay0,
        "BrightText": c.overlay1,
        "Highlight": c.surface2,
        "HighlightedText": c.overlay1,
        "Accent": c.surface2,
    }

    def row(group):
        return ", ".join("#ff" + group[role][1:] for role in ROLES)

    lines = [
        # QSettings ini files take ';' comments.
        f"; {c.name}",
        "; Generated by theming/generate.py from theming/palette.json.",
        "; Edit those, not this file.",
        "[ColorScheme]",
        f"active_colors={row(active)}",
        f"disabled_colors={row(disabled)}",
        f"inactive_colors={row(active)}",
    ]
    return {OUT: "\n".join(lines) + "\n"}
