"""Quickshell colors: config/colors.json, a flat name -> hex map the QML reads at
runtime, and config/Colors.qml, the singleton that loads it with the same
colors as defaults and exposes them as Colors.<name>."""
import json

DIR = "quickshell/.config/quickshell/config"

# A palette name from build() below
ACCENT = "purple"
# Alpha for Colors.tint(), the soft accent fill behind icons
TINT_ALPHA = 0.18


def build(c):
    colors = {
        # Backgrounds, darkest to lightest
        "bg0": c.mantle,
        "bg1": c.base,
        "bg2": c.surface0,
        "bg3": c.surface1,
        "bg4": c.surface2,
        "fg": c.text,

        "red": c.hue.red,
        "orange": c.hue.orange,
        "yellow": c.hue.yellow,
        "green": c.hue.green,
        "marker": c.marker,
        "aqua": c.hue.teal,
        "blue": c.hue.blue,
        "purple": c.hue.purple,

        # Muted text, darkest to lightest
        "gray0": c.overlay0,
        "gray1": c.overlay1,
        "gray2": c.overlay2,
    }
    defaults = "\n".join(f'      property color {name}: "{hex}"' for name, hex in colors.items())
    props = "\n".join(f"  readonly property color {name}: palette.{name}" for name in colors)
    singleton = f"""// Generated by theming/generate.py from {c.source}.
pragma Singleton
import Quickshell
import QtQuick
import Quickshell.Io

Singleton {{
  FileView {{
    path: Quickshell.shellDir + "/config/colors.json"
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {{
      id: palette

{defaults}
    }}
  }}

{props}

  readonly property color accent: {ACCENT}

  function tint(c) {{
    return Qt.alpha(c, {TINT_ALPHA})
  }}
}}
"""
    return {
        f"{DIR}/colors.json": json.dumps(colors, indent=2) + "\n",
        f"{DIR}/Colors.qml": singleton,
    }
