"""Quickshell colors: config/Colors.qml, the singleton the QML reads as
Colors.<name>. At runtime it follows caelestia-cli's active scheme
(~/.local/state/caelestia/scheme.json, reloaded when `caelestia scheme set`
rewrites it); the theme's own colors are only the fallbacks used until that
file loads or when a key is missing."""

DIR = "quickshell/.config/quickshell/config"

# Palette name -> (caelestia scheme key, fallback from the theme). The keys are
# the Catppuccin-style names every caelestia scheme carries; marker has no
# caelestia role, so it takes the bright green terminal color.
def palette(c):
    return {
        # Backgrounds, darkest to lightest
        "bg0": ("mantle", c.mantle),
        "bg1": ("base", c.base),
        "bg2": ("surface0", c.surface0),
        "bg3": ("surface1", c.surface1),
        "bg4": ("surface2", c.surface2),
        "fg": ("text", c.text),

        "red": ("red", c.hue.red),
        "orange": ("peach", c.hue.orange),
        "yellow": ("yellow", c.hue.yellow),
        "green": ("green", c.hue.green),
        "marker": ("term10", c.marker),
        "aqua": ("teal", c.hue.teal),
        "blue": ("blue", c.hue.blue),
        "purple": ("mauve", c.hue.purple),
        "accent": ("primary", c.accent),

        # Muted text, darkest to lightest
        "gray0": ("overlay0", c.overlay0),
        "gray1": ("overlay1", c.overlay1),
        "gray2": ("overlay2", c.overlay2),
    }

# Alpha for Colors.tint(), the soft accent fill behind icons
TINT_ALPHA = 0.18


def build(c):
    props = "\n".join(
        f'  readonly property color {name}: pick("{key}", "{fallback}")'
        for name, (key, fallback) in palette(c).items()
    )
    singleton = f"""// Generated by theming/generate.py from {c.source}.
pragma Singleton
import Quickshell
import QtQuick
import Quickshell.Io

Singleton {{
  id: root

  // caelestia's colours map (key -> hex without #), empty until the file loads
  property var scheme: ({{}})

  FileView {{
    path: (Quickshell.env("XDG_STATE_HOME") || Quickshell.env("HOME") + "/.local/state") + "/caelestia/scheme.json"
    watchChanges: true
    onFileChanged: reload()
    onLoaded: {{
      try {{
        root.scheme = JSON.parse(text()).colours || {{}}
      }} catch (e) {{
        console.warn("Colors: can't parse " + path + ": " + e)
      }}
    }}
  }}

  function pick(key, fallback) {{
    const hex = scheme[key]
    return hex ? "#" + hex : fallback
  }}

{props}

  function tint(c) {{
    return Qt.alpha(c, {TINT_ALPHA})
  }}
}}
"""
    return {f"{DIR}/Colors.qml": singleton}
