"""Vesktop (Vencord) theme built on refact0r's Midnight theme.

Midnight tracks Discord's frequently renamed CSS variables, so the generated
file only @imports its build and sets its color variables, the way Midnight's
own midnight.theme.css does. The layout options keep Midnight's defaults
(version 2.1.1); see https://github.com/refact0r/midnight-discord for what
each one does.
"""
from palette import alpha, blend

OUT = "vesktop/.config/vesktop/themes/{slug}.theme.css"
MIDNIGHT = "https://refact0r.github.io/midnight-discord/build/midnight.css"

# Opacity of the main panels, matching background-opacity in the ghostty config.
# Needs Vencord's "Enable window transparency" setting; Hyprland's blur is off for
# Vesktop (modules/rules.lua), so the desktop shows through unblurred.
PANEL_OPACITY = 0.75

OPTIONS = {
    "--font": "'figtree'",
    "--code-font": "''",
    "--gap": "12px",
    "--divider-thickness": "4px",
    "--border-thickness": "1px",
    "--animations": "on",
    "--list-item-transition": "0.2s ease",
    "--dms-icon-svg-transition": "0.4s ease",
    "--border-hover-transition": "0.2s ease",
    "--top-bar-height": "var(--gap)",
    "--top-bar-button-position": "titlebar",
    "--top-bar-title-position": "off",
    "--subtle-top-bar-title": "off",
    "--custom-window-controls": "on",
    "--window-control-size": "14px",
    "--custom-dms-icon": "custom",
    "--dms-icon-svg-url": "url('https://refact0r.github.io/midnight-discord/assets/Font_Awesome_5_solid_moon.svg')",
    "--dms-icon-svg-size": "90%",
    "--dms-icon-color-before": "var(--icon-subtle)",
    "--dms-icon-color-after": "var(--white)",
    "--custom-dms-background": "off",
    "--dms-background-image-url": "url('')",
    "--dms-background-image-size": "cover",
    "--dms-background-color": "linear-gradient(70deg, var(--blue-2), var(--purple-2), var(--red-2))",
    "--background-image": "off",
    "--background-image-url": "url('')",
    # Window transparency: drop Midnight's solid base layer and the elements that
    # look wrong over a see-through window
    "--transparency-tweaks": "on",
    "--remove-bg-layer": "on",
    "--panel-blur": "off",
    "--blur-amount": "12px",
    "--custom-chatbar": "off",
    "--chatbar-height": "47px",
    "--small-user-panel": "on",
}


def build(c):
    def shades(color):
        # Midnight's 1-5 steps run from lighter to darker around step 2
        return [blend(color, 0.7, c.bright), color, blend(color, 0.85, c.crust),
                blend(color, 0.7, c.crust), blend(color, 0.55, c.crust)]

    colors = {
        "--colors": "on",
        # Text, brightest first; --text-0 sits on colored elements
        "--text-0": c.crust,
        "--text-1": c.bright,
        "--text-2": c.text,
        "--text-3": c.subtext1,
        "--text-4": c.overlay2,
        "--text-5": c.overlay0,
        # Backgrounds: --bg-4 is the main area, --bg-3 the gaps behind it (like the
        # crust/mantle frame in the VSCodium target), --bg-2/1 buttons. All see-through
        # for window transparency; buttons less so, since they sit on a panel already.
        # Menus and popouts (--bg-floating) stay solid so they stay readable.
        "--bg-1": alpha(c.surface1, 0.9),
        "--bg-2": alpha(c.surface0, 0.9),
        "--bg-3": alpha(c.mantle, PANEL_OPACITY - 0.15),
        "--bg-4": alpha(c.base, PANEL_OPACITY),
        "--bg-floating": c.base,
        "--hover": alpha(c.overlay2, 0.10),
        "--active": alpha(c.overlay2, 0.20),
        "--active-2": alpha(c.overlay2, 0.30),
        "--message-hover": alpha(c.crust, 0.25),
        # Accents: links, small accents, buttons and their hover/pressed states
        "--accent-1": c.link,
        "--accent-2": c.accent,
        "--accent-3": c.accent,
        "--accent-4": blend(c.accent, 0.8, c.bright),
        "--accent-5": blend(c.accent, 0.6, c.bright),
        # Normally red in Discord, e.g. the muted/deafened buttons
        "--accent-new": c.error,
        "--online": c.success,
        "--dnd": c.error,
        "--idle": c.warning,
        "--streaming": c.hue.purple,
        "--offline": c.overlay0,
        "--button-border": alpha(c.text, 0.10),
    }
    for name in ("red", "green", "blue", "yellow", "purple"):
        for step, color in enumerate(shades(c.hue[name]), 1):
            colors[f"--{name}-{step}"] = color

    def block(selector, props):
        return [f"{selector} {{", *(f"    {k}: {v};" for k, v in props.items()), "}"]

    lines = [
        "/**",
        f" * @name {c.name}",
        f" * @description {c.name} on refact0r's Midnight. Generated by theming/generate.py from {c.source}; edit that, not this file.",
        " * @author dotfiles",
        "*/",
        "",
        f"@import url('{MIDNIGHT}');",
        "",
        *block("body", OPTIONS),
        "",
        *block(":root", colors),
    ]
    return {OUT.format(slug=c.slug): "\n".join(lines) + "\n"}
