"""Vicinae launcher theme. Only the keys set here are overridden; everything
else is inherited from the built-in vicinae-dark theme. Run
`vicinae theme template` for the full list of keys."""

OUT = "vicinae/.local/share/vicinae/themes/wisteria-dusk.toml"


def build(c):
    def q(value):
        return f'"{value}"'

    sections = {
        "meta": {
            "version": "1",
            "name": q(c.name),
            "description": q(f"{c.name}, generated from theming/palette.json"),
            "variant": q("dark"),
        },
        "colors.core": {
            "background": q(c.base),
            "secondary_background": q(c.mantle),
            "foreground": q(c.text),
            "border": q(c.surface1),
            "accent": q(c.lavender),
            "accent_foreground": q(c.base),
        },
        "colors.main_window": {
            "border": q(c.surface1),
        },
        "colors.settings_window": {
            "border": q(c.surface1),
        },
        "colors.accents": {
            "blue": q(c.blue),
            "green": q(c.green),
            "magenta": q(c.pink),
            "orange": q(c.peach),
            "purple": q(c.lavender),
            "red": q(c.red),
            "yellow": q(c.yellow),
            "cyan": q(c.sky),
        },
        "colors.text": {
            "muted": q(c.subtext0),
            "placeholder": q(c.overlay0),
            "danger": q(c.red),
            "success": q(c.mint),
            "selection": f"{{ background = {q(c.surface2)}, foreground = {q(c.text)} }}",
        },
        "colors.text.links": {
            "default": q(c.blue),
            "visited": q(c.lavender),
        },
        "colors.input": {
            "border": q(c.surface1),
            "border_focus": q(c.lavender),
            "border_error": q(c.red),
        },
        "colors.button.primary": {
            "background": q(c.surface0),
            "foreground": q(c.text),
            "hover": f"{{ background = {q(c.surface1)} }}",
            "focus": f"{{ outline = {q(c.lavender)} }}",
        },
        "colors.list.item.hover": {
            "foreground": q(c.text),
            "secondary_foreground": q(c.subtext1),
        },
        "colors.list.item.selection": {
            "background": q(c.surface0),
            "foreground": q(c.bright),
            "secondary_background": q(c.surface1),
            "secondary_foreground": q(c.subtext1),
        },
        "colors.grid.item": {
            "background": q(c.surface0),
            "hover": f"{{ outline = {q(c.overlay1)} }}",
            "selection": f"{{ outline = {q(c.lavender)} }}",
        },
        "colors.scrollbars": {
            "background": q(c.surface2),
        },
        "colors.loading": {
            "bar": q(c.mint),
            "spinner": q(c.text),
        },
    }

    lines = [
        f"# {c.name}",
        "# Generated by theming/generate.py from theming/palette.json.",
        "# Edit those, not this file.",
    ]
    for section, keys in sections.items():
        lines += ["", f"[{section}]"]
        lines += [f"{key} = {value}" for key, value in keys.items()]
    return {OUT: "\n".join(lines) + "\n"}
