"""VSCodium color theme extension: package.json plus the theme with workbench
colors, TextMate scopes and semantic tokens. Each theme gets its own extension
folder, so VSCodium lists them all in its color theme picker."""
import json

from palette import alpha

DIR = "vscodium/.vscode-oss/extensions/local.{slug}-1.0.0"


def build(c):
    colors = {
      # Base
      "foreground": c["text"], "descriptionForeground": c["subtext0"], "disabledForeground": c["overlay0"],
      "errorForeground": c.pick("error"), "focusBorder": c.pick("accent"), "icon.foreground": c["subtext1"],
      "selection.background": alpha(c.pick("accent"), .40), "widget.shadow": alpha(c["crust"], .50),
      "textLink.foreground": c.pick("link"), "textLink.activeForeground": c.pick("property"),
      "textBlockQuote.background": c["mantle"], "textBlockQuote.border": c["surface1"],
      "textCodeBlock.background": c["mantle"], "textPreformat.foreground": c.pick("string"),
      "progressBar.background": c.pick("accent"), "sash.hoverBorder": c.pick("accent"),
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": alpha(c["surface1"], .50), "scrollbarSlider.hoverBackground": c["surface1"],
      "scrollbarSlider.activeBackground": c["surface2"],

      # Title / activity / side bar: crust and mantle sit behind the editor, like Catppuccin
      "titleBar.activeBackground": c["crust"], "titleBar.activeForeground": c["text"],
      "titleBar.inactiveBackground": c["crust"], "titleBar.inactiveForeground": c["overlay1"],
      "titleBar.border": c["crust"],
      "activityBar.background": c["crust"], "activityBar.foreground": c.pick("accent"),
      "activityBar.inactiveForeground": c["overlay0"], "activityBar.activeBorder": c.pick("accent"),
      "activityBar.border": c["crust"],
      "activityBarBadge.background": c.pick("accent"), "activityBarBadge.foreground": c["crust"],
      "badge.background": c["surface1"], "badge.foreground": c["text"],
      "sideBar.background": c["mantle"], "sideBar.foreground": c["subtext0"], "sideBar.border": c["mantle"],
      "sideBarTitle.foreground": c.pick("accent"),
      "sideBarSectionHeader.background": c["mantle"], "sideBarSectionHeader.foreground": c["text"],
      "sideBarSectionHeader.border": c["surface0"],

      # Lists and trees
      "list.activeSelectionBackground": c["surface0"], "list.activeSelectionForeground": c["text"],
      "list.inactiveSelectionBackground": alpha(c["surface0"], .70), "list.inactiveSelectionForeground": c["text"],
      "list.focusBackground": c["surface0"], "list.focusForeground": c["text"],
      "list.focusOutline": "#00000000", "list.focusAndSelectionOutline": "#00000000",
      "list.hoverBackground": alpha(c["surface0"], .60), "list.hoverForeground": c["text"],
      "list.dropBackground": alpha(c.pick("accent"), .20), "list.highlightForeground": c.pick("accent"),
      "list.errorForeground": c.pick("error"), "list.warningForeground": c.pick("hue.orange"),
      "tree.indentGuidesStroke": c["surface1"], "tree.inactiveIndentGuidesStroke": c["surface0"],

      # Editor
      "editor.background": c["base"], "editor.foreground": c["text"],
      "editorCursor.foreground": c.pick("marker"),
      "editor.selectionBackground": alpha(c["overlay2"], .25),
      "editor.inactiveSelectionBackground": alpha(c["overlay2"], .15),
      "editor.selectionHighlightBackground": alpha(c["overlay2"], .15),
      "editor.wordHighlightBackground": alpha(c["overlay2"], .18),
      "editor.wordHighlightStrongBackground": alpha(c.pick("secondary"), .20),
      "editor.lineHighlightBackground": alpha(c["text"], .05),
      "editor.lineHighlightBorder": "#00000000",
      "editor.findMatchBackground": alpha(c.pick("parameter"), .40), "editor.findMatchBorder": alpha(c.pick("parameter"), .80),
      "editor.findMatchHighlightBackground": alpha(c.pick("search"), .25),
      "editor.findRangeHighlightBackground": alpha(c["surface1"], .50),
      "editor.rangeHighlightBackground": alpha(c["surface1"], .40),
      "editor.hoverHighlightBackground": alpha(c["surface1"], .40),
      "editor.foldBackground": alpha(c.pick("secondary"), .10),
      "editorLink.activeForeground": c.pick("accent"),
      "editorLineNumber.foreground": c["surface2"], "editorLineNumber.activeForeground": c.pick("marker"),
      "editorIndentGuide.background1": c["surface1"], "editorIndentGuide.activeBackground1": c["overlay0"],
      "editorWhitespace.foreground": alpha(c["overlay2"], .40),
      "editorRuler.foreground": c["surface1"],
      "editorCodeLens.foreground": c["overlay1"],
      "editorInlayHint.foreground": c["overlay1"], "editorInlayHint.background": alpha(c["surface0"], .70),
      "editorBracketMatch.background": alpha(c["overlay2"], .15), "editorBracketMatch.border": c["overlay2"],
      "editorBracketHighlight.foreground1": c.pick("hue.red"), "editorBracketHighlight.foreground2": c.pick("hue.orange"),
      "editorBracketHighlight.foreground3": c.pick("hue.yellow"), "editorBracketHighlight.foreground4": c.pick("hue.green"),
      "editorBracketHighlight.foreground5": c.pick("label"), "editorBracketHighlight.foreground6": c.pick("hue.purple"),
      "editorBracketHighlight.unexpectedBracket.foreground": c.pick("parameter"),
      "editorError.foreground": c.pick("error"), "editorWarning.foreground": c.pick("warning"),
      "editorInfo.foreground": c.pick("info"), "editorHint.foreground": c.pick("hint"),
      "problemsErrorIcon.foreground": c.pick("error"), "problemsWarningIcon.foreground": c.pick("warning"),
      "problemsInfoIcon.foreground": c.pick("info"),
      "editorUnnecessaryCode.opacity": "#00000080",
      "editorGutter.background": c["base"],
      "editorGutter.addedBackground": c.pick("added"), "editorGutter.modifiedBackground": c.pick("modified"),
      "editorGutter.deletedBackground": c.pick("removed"),
      "editorOverviewRuler.border": alpha(c["text"], .07),
      "editorOverviewRuler.errorForeground": c.pick("error"), "editorOverviewRuler.warningForeground": c.pick("warning"),
      "editorOverviewRuler.infoForeground": c.pick("info"),
      "editorOverviewRuler.addedForeground": alpha(c.pick("added"), .60),
      "editorOverviewRuler.modifiedForeground": alpha(c.pick("hue.yellow"), .60),
      "editorOverviewRuler.deletedForeground": alpha(c.pick("removed"), .60),
      "editorOverviewRuler.findMatchForeground": c.pick("parameter"),
      "minimap.background": alpha(c["mantle"], .80),
      "minimap.findMatchHighlight": alpha(c.pick("search"), .30), "minimap.selectionHighlight": alpha(c["surface2"], .75),
      "minimapGutter.addedBackground": alpha(c.pick("added"), .75), "minimapGutter.modifiedBackground": alpha(c.pick("hue.yellow"), .75),
      "minimapGutter.deletedBackground": alpha(c.pick("removed"), .75),

      # Widgets
      "editorWidget.background": c["mantle"], "editorWidget.foreground": c["text"],
      "editorWidget.border": c["surface1"], "editorWidget.resizeBorder": c["surface2"],
      "editorHoverWidget.background": c["mantle"], "editorHoverWidget.border": c["surface2"],
      "editorSuggestWidget.background": c["mantle"], "editorSuggestWidget.border": c["surface2"],
      "editorSuggestWidget.foreground": c["text"], "editorSuggestWidget.highlightForeground": c.pick("accent"),
      "editorSuggestWidget.selectedBackground": c["surface0"],
      "editorSuggestWidget.focusHighlightForeground": c.pick("property"),
      "quickInput.background": c["mantle"], "quickInput.foreground": c["text"],
      "quickInputList.focusBackground": c["surface0"], "quickInputTitle.background": c["mantle"],
      "pickerGroup.foreground": c.pick("accent"), "pickerGroup.border": c["surface1"],
      "peekView.border": c.pick("accent"),
      "peekViewEditor.background": c["mantle"], "peekViewEditor.matchHighlightBackground": alpha(c.pick("search"), .25),
      "peekViewResult.background": c["mantle"], "peekViewResult.selectionBackground": c["surface0"],
      "peekViewResult.matchHighlightBackground": alpha(c.pick("search"), .25),
      "peekViewTitle.background": c["base"], "peekViewTitleLabel.foreground": c["text"],
      "peekViewTitleDescription.foreground": c["subtext0"],
      "notifications.background": c["mantle"], "notifications.foreground": c["text"],
      "notifications.border": c["surface0"], "notificationCenterHeader.background": c["mantle"],
      "notificationLink.foreground": c.pick("link"),
      "notificationsErrorIcon.foreground": c.pick("error"), "notificationsWarningIcon.foreground": c.pick("warning"),
      "notificationsInfoIcon.foreground": c.pick("info"),
      "menu.background": c["mantle"], "menu.foreground": c["text"], "menu.border": c["surface0"],
      "menu.selectionBackground": c["surface0"], "menu.selectionForeground": c["text"],
      "menu.separatorBackground": c["surface1"],
      "menubar.selectionBackground": c["surface0"],

      # Inputs and buttons
      "input.background": c["surface0"], "input.foreground": c["text"], "input.border": "#00000000",
      "input.placeholderForeground": c["overlay1"],
      "inputOption.activeBackground": c["surface2"], "inputOption.activeBorder": c.pick("accent"),
      "inputOption.activeForeground": c["text"],
      "inputValidation.errorBackground": c["mantle"], "inputValidation.errorBorder": c.pick("error"),
      "inputValidation.warningBackground": c["mantle"], "inputValidation.warningBorder": c.pick("warning"),
      "inputValidation.infoBackground": c["mantle"], "inputValidation.infoBorder": c.pick("info"),
      "dropdown.background": c["mantle"], "dropdown.listBackground": c["surface0"],
      "dropdown.border": c["surface1"], "dropdown.foreground": c["text"],
      "button.background": c.pick("accent"), "button.foreground": c["crust"],
      "button.hoverBackground": c.pick("property"), "button.border": "#00000000",
      "button.secondaryBackground": c["surface1"], "button.secondaryForeground": c["text"],
      "button.secondaryHoverBackground": c["surface2"],
      "checkbox.background": c["surface0"], "checkbox.border": c["surface1"], "checkbox.foreground": c.pick("accent"),
      "keybindingLabel.background": c["surface0"], "keybindingLabel.foreground": c["text"],
      "keybindingLabel.border": c["surface1"], "keybindingLabel.bottomBorder": c["surface1"],

      # Tabs and editor groups
      "editorGroup.border": c["surface1"], "editorGroup.dropBackground": alpha(c.pick("accent"), .20),
      "editorGroupHeader.tabsBackground": c["crust"], "editorGroupHeader.noTabsBackground": c["crust"],
      "editorGroupHeader.tabsBorder": c["crust"],
      "tab.activeBackground": c["base"], "tab.activeForeground": c.pick("accent"),
      "tab.activeBorder": "#00000000", "tab.activeBorderTop": c.pick("marker"),
      "tab.unfocusedActiveBackground": c["base"], "tab.unfocusedActiveForeground": c["subtext0"],
      "tab.unfocusedActiveBorderTop": c["surface2"],
      "tab.inactiveBackground": c["mantle"], "tab.inactiveForeground": c["overlay1"],
      "tab.unfocusedInactiveForeground": c["overlay0"],
      "tab.hoverBackground": c["surface0"], "tab.border": c["crust"],
      "tab.activeModifiedBorder": c.pick("hue.yellow"), "tab.inactiveModifiedBorder": alpha(c.pick("hue.yellow"), .50),
      "breadcrumb.foreground": c["subtext0"], "breadcrumb.focusForeground": c.pick("accent"),
      "breadcrumb.activeSelectionForeground": c.pick("accent"), "breadcrumb.background": c["base"],
      "breadcrumbPicker.background": c["mantle"],

      # Panel, terminal, status bar
      "panel.background": c["base"], "panel.border": c["surface1"],
      "panelTitle.activeForeground": c["text"], "panelTitle.inactiveForeground": c["overlay1"],
      "panelTitle.activeBorder": c.pick("accent"),
      "panelSection.border": c["surface1"],
      "statusBar.background": c["crust"], "statusBar.foreground": c["subtext1"], "statusBar.border": c["crust"],
      "statusBar.noFolderBackground": c["crust"], "statusBar.noFolderForeground": c["subtext1"],
      "statusBar.debuggingBackground": c.pick("hue.orange"), "statusBar.debuggingForeground": c["crust"],
      "statusBarItem.hoverBackground": c["surface0"], "statusBarItem.activeBackground": c["surface1"],
      "statusBarItem.remoteBackground": c.pick("accent"), "statusBarItem.remoteForeground": c["crust"],
      "statusBarItem.errorBackground": c.pick("urgent"), "statusBarItem.errorForeground": c["bright"],
      "statusBarItem.prominentBackground": c["surface1"],
      "terminal.background": c["base"], "terminal.foreground": c["text"],
      "terminalCursor.foreground": c.pick("marker"), "terminalCursor.background": c["base"],
      "terminal.selectionBackground": c["surface2"],
      "terminal.findMatchBackground": alpha(c.pick("parameter"), .40),
      "terminal.findMatchHighlightBackground": alpha(c.pick("search"), .25),

      # Git and diff
      "gitDecoration.addedResourceForeground": c.pick("added"),
      "gitDecoration.modifiedResourceForeground": c.pick("modified"),
      "gitDecoration.deletedResourceForeground": c.pick("removed"),
      "gitDecoration.renamedResourceForeground": c.pick("changed"),
      "gitDecoration.untrackedResourceForeground": c.pick("added"),
      "gitDecoration.ignoredResourceForeground": c["overlay0"],
      "gitDecoration.conflictingResourceForeground": c.pick("special"),
      "gitDecoration.submoduleResourceForeground": c.pick("label"),
      "gitDecoration.stageModifiedResourceForeground": c.pick("modified"),
      "gitDecoration.stageDeletedResourceForeground": c.pick("removed"),
      "diffEditor.insertedTextBackground": alpha(c.pick("added"), .12),
      "diffEditor.removedTextBackground": alpha(c.pick("removed"), .12),
      "diffEditor.insertedLineBackground": alpha(c.pick("added"), .10),
      "diffEditor.removedLineBackground": alpha(c.pick("removed"), .10),
      "diffEditor.diagonalFill": alpha(c["surface2"], .60),
      "merge.currentHeaderBackground": alpha(c.pick("added"), .40), "merge.currentContentBackground": alpha(c.pick("added"), .15),
      "merge.incomingHeaderBackground": alpha(c.pick("changed"), .40), "merge.incomingContentBackground": alpha(c.pick("changed"), .15),

      # Debugging
      "debugToolBar.background": c["crust"],
      "debugIcon.breakpointForeground": c.pick("error"),
      "editor.stackFrameHighlightBackground": alpha(c.pick("warning"), .15),
      "editor.focusedStackFrameHighlightBackground": alpha(c.pick("success"), .15),
    }
    names = ["Black","Red","Green","Yellow","Blue","Magenta","Cyan","White"]
    for i, col in enumerate(c.ansi):
        colors[f"terminal.ansi{'Bright' if i >= 8 else ''}{names[i % 8]}"] = col

    def tok(scope, fg=None, style=None):
        s = {}
        if fg: s["foreground"] = c.pick(fg)
        if style is not None: s["fontStyle"] = style
        return {"scope": scope, "settings": s}

    tokenColors = [
      tok(["comment", "punctuation.definition.comment"], "overlay2", "italic"),
      tok(["comment.block.documentation", "comment.line.documentation"], "overlay2", "italic"),
      tok(["storage.type.class.jsdoc", "entity.name.type.instance.jsdoc"], "keyword", "italic"),
      tok(["string", "string.quoted", "string.template", "punctuation.definition.string"], "string"),
      tok(["string.regexp"], "special"),
      tok(["constant.character.escape", "constant.other.placeholder", "punctuation.definition.template-expression"], "special"),
      tok(["constant.character", "string.quoted.single.char"], "character"),
      tok(["constant.numeric", "constant.language", "constant.language.boolean", "constant.other"], "constant"),
      tok(["variable.other.constant", "variable.other.enummember"], "constant"),
      tok(["keyword", "keyword.control", "storage", "storage.type", "storage.modifier", "keyword.other"], "keyword", ""),
      tok(["keyword.operator.new", "keyword.operator.expression", "keyword.operator.logical.python", "keyword.operator.word"], "keyword"),
      tok(["keyword.operator", "punctuation.accessor", "punctuation.separator.key-value"], "operator"),
      tok(["keyword.control.directive", "punctuation.definition.directive", "meta.preprocessor", "entity.name.function.preprocessor"], "special"),
      tok(["entity.name.function", "support.function", "meta.function-call.generic", "variable.function"], "function"),
      tok(["support.function.builtin", "support.function.misc", "entity.name.function.macro"], "constant"),
      tok(["entity.name.type", "entity.name.class", "entity.other.inherited-class", "support.class", "support.type", "entity.name.type.class"], "type"),
      tok(["support.type.primitive", "support.type.builtin", "storage.type.primitive", "storage.type.built-in", "keyword.type"], "keyword"),
      tok(["entity.name.namespace", "entity.name.type.namespace", "entity.name.type.module", "storage.modifier.import", "storage.modifier.package"], "module", "italic"),
      tok(["variable", "variable.other", "variable.other.readwrite", "meta.definition.variable.name"], "text"),
      tok(["variable.parameter", "meta.parameter", "variable.parameter.function"], "parameter", "italic"),
      tok(["variable.language", "variable.language.this", "variable.language.self", "variable.language.super"], "builtin", "italic"),
      tok(["variable.other.property", "variable.other.object.property", "support.variable.property", "meta.object-literal.key", "entity.name.variable.field"], "property"),
      tok(["support.type.property-name", "support.type.property-name.json", "support.type.property-name.toml"], "function"),
      tok(["support.type.property-name.css", "support.type.vendored.property-name.css"], "function"),
      tok(["entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"], "type"),
      tok(["entity.name.tag.css", "entity.other.attribute-name.pseudo-class.css"], "property"),
      tok(["punctuation", "meta.brace", "punctuation.terminator", "punctuation.separator"], "overlay2"),
      tok(["entity.name.tag", "support.tag"], "function"),
      tok(["entity.other.attribute-name"], "module", "italic"),
      tok(["punctuation.definition.tag"], "character"),
      tok(["entity.name.label", "keyword.control.label"], "label"),
      tok(["meta.decorator", "punctuation.decorator", "storage.type.annotation", "entity.name.function.decorator"], "constant"),
      tok(["invalid", "invalid.illegal"], "error"),
      tok(["invalid.deprecated"], "overlay1", "strikethrough"),
      tok(["markup.heading", "entity.name.section"], "secondary", "bold"),
      tok(["markup.heading.1", "heading.1.markdown"], "hue.red", "bold"),
      tok(["markup.heading.2", "heading.2.markdown"], "hue.orange", "bold"),
      tok(["markup.heading.3", "heading.3.markdown"], "hue.yellow", "bold"),
      tok(["markup.heading.4", "heading.4.markdown"], "hue.green", "bold"),
      tok(["markup.heading.5", "heading.5.markdown"], "label", "bold"),
      tok(["markup.heading.6", "heading.6.markdown"], "property", "bold"),
      tok(["markup.bold"], "parameter", "bold"),
      tok(["markup.italic"], "parameter", "italic"),
      tok(["markup.strikethrough"], "subtext0", "strikethrough"),
      tok(["markup.underline.link", "markup.underline.link.image", "string.other.link"], "link", "underline"),
      tok(["markup.inline.raw", "markup.fenced_code", "markup.raw"], "string"),
      tok(["markup.quote"], "special", "italic"),
      tok(["markup.list punctuation.definition.list.begin", "punctuation.definition.list.begin.markdown"], "character"),
      tok(["markup.inserted", "meta.diff.header.to-file", "punctuation.definition.inserted"], "added"),
      tok(["markup.deleted", "meta.diff.header.from-file", "punctuation.definition.deleted"], "removed"),
      tok(["markup.changed", "punctuation.definition.changed"], "changed"),
      tok(["meta.diff.range", "meta.diff.header"], "overlay1"),

      # Wider language coverage
      tok(["entity.name.function.member", "support.function.any-method", "meta.method-call entity.name.function", "variable.function"], "function"),
      tok(["meta.function-call.generic", "meta.function-call.python"], "function"),
      tok(["entity.name.function.constructor", "support.class.builtin"], "type"),
      tok(["entity.name.type.parameter", "storage.type.generic"], "parameter", "italic"),
      tok(["variable.parameter.function.language.special.self", "variable.language.special.self", "variable.language.special.cls"], "builtin", "italic"),
      tok(["support.constant", "constant.other.color", "keyword.other.unit", "constant.other.symbol"], "constant"),
      tok(["support.variable", "variable.other.predefined"], "builtin"),
      tok(["support.function.builtin.shell", "support.function.builtin.python"], "constant"),
      tok(["variable.other.normal.shell", "variable.other.positional.shell", "variable.other.special.shell"], "parameter"),
      tok(["punctuation.definition.variable.shell", "punctuation.definition.evaluation.backticks.shell"], "special"),
      tok(["punctuation.section.embedded", "punctuation.definition.interpolation", "punctuation.definition.template-expression.begin", "punctuation.definition.template-expression.end"], "special"),
      tok(["meta.embedded", "source.groovy.embedded", "meta.template.expression"], "text"),
      tok(["keyword.operator.assignment", "keyword.operator.arithmetic", "keyword.operator.comparison", "keyword.operator.relational", "storage.type.function.arrow"], "operator"),
      tok(["punctuation.definition.parameters", "punctuation.definition.arguments", "punctuation.section"], "overlay2"),
      tok(["entity.name.tag.yaml", "punctuation.support.type.property-name"], "function"),
      tok(["string.unquoted.plain.out.yaml", "string.unquoted.yaml"], "string"),
      tok(["entity.name.section.group-title.ini", "entity.name.tag.table.toml"], "keyword", "bold"),
      tok(["punctuation.definition.heading.markdown", "punctuation.definition.bold.markdown", "punctuation.definition.italic.markdown"], "overlay2"),
      tok(["fenced_code.block.language", "markup.fenced_code.block.language"], "property", "italic"),
      tok(["markup.inline.raw.string.markdown"], "string"),
    ]

    semantic = {
      "enumMember": c.pick("character"), "selfKeyword": {"foreground": c.pick("builtin"), "italic": True},
      "parameter": {"foreground": c.pick("parameter"), "italic": True},
      "variable.defaultLibrary": c.pick("builtin"), "variable.readonly.defaultLibrary": c.pick("constant"),
      "property": c.pick("property"), "property.readonly": c.pick("property"),
      "function.defaultLibrary": c.pick("constant"), "method.defaultLibrary": c.pick("constant"),
      "namespace": {"foreground": c.pick("module"), "italic": True},
      "type": c.pick("type"), "class": c.pick("type"), "interface": c.pick("type"), "struct": c.pick("type"),
      "enum": c.pick("type"), "typeParameter": {"foreground": c.pick("parameter"), "italic": True},
      "type.defaultLibrary": c.pick("keyword"), "class.defaultLibrary": c.pick("type"),
      "macro": c.pick("special"), "decorator": c.pick("constant"), "builtinAttribute": c.pick("constant"),
      "comment": {"foreground": c["overlay2"], "italic": True}, "label": c.pick("label"),
      "lifetime": {"foreground": c.pick("builtin"), "italic": True},
    }

    theme = {
      "$schema": "vscode://schemas/color-theme",
      "name": c.name, "type": c.variant,
      "semanticHighlighting": True,
      "colors": colors, "tokenColors": tokenColors, "semanticTokenColors": semantic,
    }
    theme_file = f"themes/{c.slug}-color-theme.json"
    package = {
      "name": c.slug,
      "displayName": c.name,
      "description": f"{c.name} for VSCode",
      "version": "1.0.0",
      "publisher": "local",
      "engines": {"vscode": "^1.80.0"},
      "categories": ["Themes"],
      "contributes": {"themes": [{
        "label": c.name,
        "uiTheme": "vs-dark" if c.variant == "dark" else "vs",
        "path": f"./{theme_file}",
      }]},
    }
    out = DIR.format(slug=c.slug)
    return {
      f"{out}/package.json": json.dumps(package, indent=2),
      f"{out}/{theme_file}": json.dumps(theme, indent=2) + "\n",
    }
