"""VSCodium color theme: workbench colors, TextMate scopes and semantic tokens."""
import json

from palette import alpha

OUT = "vscodium/.vscode-oss/extensions/local.wisteria-dusk-1.0.0/themes/wisteria-dusk-color-theme.json"


def build(c):
    colors = {
      # Base
      "foreground": c["text"], "descriptionForeground": c["subtext0"], "disabledForeground": c["overlay0"],
      "errorForeground": c["red"], "focusBorder": c["lavender"], "icon.foreground": c["subtext1"],
      "selection.background": alpha(c["lavender"], .40), "widget.shadow": alpha(c["crust"], .50),
      "textLink.foreground": c["blue"], "textLink.activeForeground": c["lilac"],
      "textBlockQuote.background": c["mantle"], "textBlockQuote.border": c["surface1"],
      "textCodeBlock.background": c["mantle"], "textPreformat.foreground": c["green"],
      "progressBar.background": c["lavender"], "sash.hoverBorder": c["lavender"],
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": alpha(c["surface1"], .50), "scrollbarSlider.hoverBackground": c["surface1"],
      "scrollbarSlider.activeBackground": c["surface2"],

      # Title / activity / side bar: crust and mantle sit behind the editor, like Catppuccin
      "titleBar.activeBackground": c["crust"], "titleBar.activeForeground": c["text"],
      "titleBar.inactiveBackground": c["crust"], "titleBar.inactiveForeground": c["overlay1"],
      "titleBar.border": c["crust"],
      "activityBar.background": c["crust"], "activityBar.foreground": c["lavender"],
      "activityBar.inactiveForeground": c["overlay0"], "activityBar.activeBorder": c["lavender"],
      "activityBar.border": c["crust"],
      "activityBarBadge.background": c["lavender"], "activityBarBadge.foreground": c["crust"],
      "badge.background": c["surface1"], "badge.foreground": c["text"],
      "sideBar.background": c["mantle"], "sideBar.foreground": c["subtext0"], "sideBar.border": c["mantle"],
      "sideBarTitle.foreground": c["lavender"],
      "sideBarSectionHeader.background": c["mantle"], "sideBarSectionHeader.foreground": c["text"],
      "sideBarSectionHeader.border": c["surface0"],

      # Lists and trees
      "list.activeSelectionBackground": c["surface0"], "list.activeSelectionForeground": c["text"],
      "list.inactiveSelectionBackground": alpha(c["surface0"], .70), "list.inactiveSelectionForeground": c["text"],
      "list.focusBackground": c["surface0"], "list.focusForeground": c["text"],
      "list.focusOutline": "#00000000", "list.focusAndSelectionOutline": "#00000000",
      "list.hoverBackground": alpha(c["surface0"], .60), "list.hoverForeground": c["text"],
      "list.dropBackground": alpha(c["lavender"], .20), "list.highlightForeground": c["lavender"],
      "list.errorForeground": c["red"], "list.warningForeground": c["peach"],
      "tree.indentGuidesStroke": c["surface1"], "tree.inactiveIndentGuidesStroke": c["surface0"],

      # Editor
      "editor.background": c["base"], "editor.foreground": c["text"],
      "editorCursor.foreground": c["mint"],
      "editor.selectionBackground": alpha(c["overlay2"], .25),
      "editor.inactiveSelectionBackground": alpha(c["overlay2"], .15),
      "editor.selectionHighlightBackground": alpha(c["overlay2"], .15),
      "editor.wordHighlightBackground": alpha(c["overlay2"], .18),
      "editor.wordHighlightStrongBackground": alpha(c["blue"], .20),
      "editor.lineHighlightBackground": alpha(c["text"], .05),
      "editor.lineHighlightBorder": "#00000000",
      "editor.findMatchBackground": alpha(c["maroon"], .40), "editor.findMatchBorder": alpha(c["maroon"], .80),
      "editor.findMatchHighlightBackground": alpha(c["sky"], .25),
      "editor.findRangeHighlightBackground": alpha(c["surface1"], .50),
      "editor.rangeHighlightBackground": alpha(c["surface1"], .40),
      "editor.hoverHighlightBackground": alpha(c["surface1"], .40),
      "editor.foldBackground": alpha(c["blue"], .10),
      "editorLink.activeForeground": c["lavender"],
      "editorLineNumber.foreground": c["surface2"], "editorLineNumber.activeForeground": c["lavender"],
      "editorIndentGuide.background1": c["surface1"], "editorIndentGuide.activeBackground1": c["overlay0"],
      "editorWhitespace.foreground": alpha(c["overlay2"], .40),
      "editorRuler.foreground": c["surface1"],
      "editorCodeLens.foreground": c["overlay1"],
      "editorInlayHint.foreground": c["overlay1"], "editorInlayHint.background": alpha(c["surface0"], .70),
      "editorBracketMatch.background": alpha(c["overlay2"], .15), "editorBracketMatch.border": c["overlay2"],
      "editorBracketHighlight.foreground1": c["red"], "editorBracketHighlight.foreground2": c["peach"],
      "editorBracketHighlight.foreground3": c["yellow"], "editorBracketHighlight.foreground4": c["green"],
      "editorBracketHighlight.foreground5": c["sapphire"], "editorBracketHighlight.foreground6": c["lavender"],
      "editorBracketHighlight.unexpectedBracket.foreground": c["maroon"],
      "editorError.foreground": c["red"], "editorWarning.foreground": c["yellow"],
      "editorInfo.foreground": c["sky"], "editorHint.foreground": c["teal"],
      "problemsErrorIcon.foreground": c["red"], "problemsWarningIcon.foreground": c["yellow"],
      "problemsInfoIcon.foreground": c["sky"],
      "editorUnnecessaryCode.opacity": "#00000080",
      "editorGutter.background": c["base"],
      "editorGutter.addedBackground": c["green"], "editorGutter.modifiedBackground": c["ochre"],
      "editorGutter.deletedBackground": c["red"],
      "editorOverviewRuler.border": alpha(c["text"], .07),
      "editorOverviewRuler.errorForeground": c["red"], "editorOverviewRuler.warningForeground": c["yellow"],
      "editorOverviewRuler.infoForeground": c["sky"],
      "editorOverviewRuler.addedForeground": alpha(c["green"], .60),
      "editorOverviewRuler.modifiedForeground": alpha(c["yellow"], .60),
      "editorOverviewRuler.deletedForeground": alpha(c["red"], .60),
      "editorOverviewRuler.findMatchForeground": c["maroon"],
      "minimap.background": alpha(c["mantle"], .80),
      "minimap.findMatchHighlight": alpha(c["sky"], .30), "minimap.selectionHighlight": alpha(c["surface2"], .75),
      "minimapGutter.addedBackground": alpha(c["green"], .75), "minimapGutter.modifiedBackground": alpha(c["yellow"], .75),
      "minimapGutter.deletedBackground": alpha(c["red"], .75),

      # Widgets
      "editorWidget.background": c["mantle"], "editorWidget.foreground": c["text"],
      "editorWidget.border": c["surface1"], "editorWidget.resizeBorder": c["surface2"],
      "editorHoverWidget.background": c["mantle"], "editorHoverWidget.border": c["surface2"],
      "editorSuggestWidget.background": c["mantle"], "editorSuggestWidget.border": c["surface2"],
      "editorSuggestWidget.foreground": c["text"], "editorSuggestWidget.highlightForeground": c["lavender"],
      "editorSuggestWidget.selectedBackground": c["surface0"],
      "editorSuggestWidget.focusHighlightForeground": c["lilac"],
      "quickInput.background": c["mantle"], "quickInput.foreground": c["text"],
      "quickInputList.focusBackground": c["surface0"], "quickInputTitle.background": c["mantle"],
      "pickerGroup.foreground": c["lavender"], "pickerGroup.border": c["surface1"],
      "peekView.border": c["lavender"],
      "peekViewEditor.background": c["mantle"], "peekViewEditor.matchHighlightBackground": alpha(c["sky"], .25),
      "peekViewResult.background": c["mantle"], "peekViewResult.selectionBackground": c["surface0"],
      "peekViewResult.matchHighlightBackground": alpha(c["sky"], .25),
      "peekViewTitle.background": c["base"], "peekViewTitleLabel.foreground": c["text"],
      "peekViewTitleDescription.foreground": c["subtext0"],
      "notifications.background": c["mantle"], "notifications.foreground": c["text"],
      "notifications.border": c["surface0"], "notificationCenterHeader.background": c["mantle"],
      "notificationLink.foreground": c["blue"],
      "notificationsErrorIcon.foreground": c["red"], "notificationsWarningIcon.foreground": c["yellow"],
      "notificationsInfoIcon.foreground": c["sky"],
      "menu.background": c["mantle"], "menu.foreground": c["text"], "menu.border": c["surface0"],
      "menu.selectionBackground": c["surface0"], "menu.selectionForeground": c["text"],
      "menu.separatorBackground": c["surface1"],
      "menubar.selectionBackground": c["surface0"],

      # Inputs and buttons
      "input.background": c["surface0"], "input.foreground": c["text"], "input.border": "#00000000",
      "input.placeholderForeground": c["overlay1"],
      "inputOption.activeBackground": c["surface2"], "inputOption.activeBorder": c["lavender"],
      "inputOption.activeForeground": c["text"],
      "inputValidation.errorBackground": c["mantle"], "inputValidation.errorBorder": c["red"],
      "inputValidation.warningBackground": c["mantle"], "inputValidation.warningBorder": c["yellow"],
      "inputValidation.infoBackground": c["mantle"], "inputValidation.infoBorder": c["sky"],
      "dropdown.background": c["mantle"], "dropdown.listBackground": c["surface0"],
      "dropdown.border": c["surface1"], "dropdown.foreground": c["text"],
      "button.background": c["lavender"], "button.foreground": c["crust"],
      "button.hoverBackground": c["lilac"], "button.border": "#00000000",
      "button.secondaryBackground": c["surface1"], "button.secondaryForeground": c["text"],
      "button.secondaryHoverBackground": c["surface2"],
      "checkbox.background": c["surface0"], "checkbox.border": c["surface1"], "checkbox.foreground": c["lavender"],
      "keybindingLabel.background": c["surface0"], "keybindingLabel.foreground": c["text"],
      "keybindingLabel.border": c["surface1"], "keybindingLabel.bottomBorder": c["surface1"],

      # Tabs and editor groups
      "editorGroup.border": c["surface1"], "editorGroup.dropBackground": alpha(c["lavender"], .20),
      "editorGroupHeader.tabsBackground": c["crust"], "editorGroupHeader.noTabsBackground": c["crust"],
      "editorGroupHeader.tabsBorder": c["crust"],
      "tab.activeBackground": c["base"], "tab.activeForeground": c["lavender"],
      "tab.activeBorder": "#00000000", "tab.activeBorderTop": c["lavender"],
      "tab.unfocusedActiveBackground": c["base"], "tab.unfocusedActiveForeground": c["subtext0"],
      "tab.unfocusedActiveBorderTop": c["surface2"],
      "tab.inactiveBackground": c["mantle"], "tab.inactiveForeground": c["overlay1"],
      "tab.unfocusedInactiveForeground": c["overlay0"],
      "tab.hoverBackground": c["surface0"], "tab.border": c["crust"],
      "tab.activeModifiedBorder": c["yellow"], "tab.inactiveModifiedBorder": alpha(c["yellow"], .50),
      "breadcrumb.foreground": c["subtext0"], "breadcrumb.focusForeground": c["lavender"],
      "breadcrumb.activeSelectionForeground": c["lavender"], "breadcrumb.background": c["base"],
      "breadcrumbPicker.background": c["mantle"],

      # Panel, terminal, status bar
      "panel.background": c["base"], "panel.border": c["surface1"],
      "panelTitle.activeForeground": c["text"], "panelTitle.inactiveForeground": c["overlay1"],
      "panelTitle.activeBorder": c["lavender"],
      "panelSection.border": c["surface1"],
      "statusBar.background": c["crust"], "statusBar.foreground": c["subtext1"], "statusBar.border": c["crust"],
      "statusBar.noFolderBackground": c["crust"], "statusBar.noFolderForeground": c["subtext1"],
      "statusBar.debuggingBackground": c["peach"], "statusBar.debuggingForeground": c["crust"],
      "statusBarItem.hoverBackground": c["surface0"], "statusBarItem.activeBackground": c["surface1"],
      "statusBarItem.remoteBackground": c["lavender"], "statusBarItem.remoteForeground": c["crust"],
      "statusBarItem.errorBackground": c["oxblood"], "statusBarItem.errorForeground": c["bright"],
      "statusBarItem.prominentBackground": c["surface1"],
      "terminal.background": c["base"], "terminal.foreground": c["text"],
      "terminalCursor.foreground": c["mint"], "terminalCursor.background": c["base"],
      "terminal.selectionBackground": c["surface2"],
      "terminal.findMatchBackground": alpha(c["maroon"], .40),
      "terminal.findMatchHighlightBackground": alpha(c["sky"], .25),

      # Git and diff
      "gitDecoration.addedResourceForeground": c["green"],
      "gitDecoration.modifiedResourceForeground": c["ochre"],
      "gitDecoration.deletedResourceForeground": c["red"],
      "gitDecoration.renamedResourceForeground": c["blue"],
      "gitDecoration.untrackedResourceForeground": c["green"],
      "gitDecoration.ignoredResourceForeground": c["overlay0"],
      "gitDecoration.conflictingResourceForeground": c["pink"],
      "gitDecoration.submoduleResourceForeground": c["sapphire"],
      "gitDecoration.stageModifiedResourceForeground": c["ochre"],
      "gitDecoration.stageDeletedResourceForeground": c["red"],
      "diffEditor.insertedTextBackground": alpha(c["green"], .12),
      "diffEditor.removedTextBackground": alpha(c["red"], .12),
      "diffEditor.insertedLineBackground": alpha(c["green"], .10),
      "diffEditor.removedLineBackground": alpha(c["red"], .10),
      "diffEditor.diagonalFill": alpha(c["surface2"], .60),
      "merge.currentHeaderBackground": alpha(c["green"], .40), "merge.currentContentBackground": alpha(c["green"], .15),
      "merge.incomingHeaderBackground": alpha(c["blue"], .40), "merge.incomingContentBackground": alpha(c["blue"], .15),

      # Debugging
      "debugToolBar.background": c["crust"],
      "debugIcon.breakpointForeground": c["red"],
      "editor.stackFrameHighlightBackground": alpha(c["yellow"], .15),
      "editor.focusedStackFrameHighlightBackground": alpha(c["green"], .15),
    }
    names = ["Black","Red","Green","Yellow","Blue","Magenta","Cyan","White"]
    for i, col in enumerate(c.ansi):
        colors[f"terminal.ansi{'Bright' if i >= 8 else ''}{names[i % 8]}"] = col

    def tok(scope, fg=None, style=None):
        s = {}
        if fg: s["foreground"] = c[fg]
        if style is not None: s["fontStyle"] = style
        return {"scope": scope, "settings": s}

    tokenColors = [
      tok(["comment", "punctuation.definition.comment"], "overlay2", "italic"),
      tok(["comment.block.documentation", "comment.line.documentation"], "overlay2", "italic"),
      tok(["storage.type.class.jsdoc", "entity.name.type.instance.jsdoc"], "lavender", "italic"),
      tok(["string", "string.quoted", "string.template", "punctuation.definition.string"], "green"),
      tok(["string.regexp"], "pink"),
      tok(["constant.character.escape", "constant.other.placeholder", "punctuation.definition.template-expression"], "pink"),
      tok(["constant.character", "string.quoted.single.char"], "teal"),
      tok(["constant.numeric", "constant.language", "constant.language.boolean", "constant.other"], "peach"),
      tok(["variable.other.constant", "variable.other.enummember"], "peach"),
      tok(["keyword", "keyword.control", "storage", "storage.type", "storage.modifier", "keyword.other"], "lavender", ""),
      tok(["keyword.operator.new", "keyword.operator.expression", "keyword.operator.logical.python", "keyword.operator.word"], "lavender"),
      tok(["keyword.operator", "punctuation.accessor", "punctuation.separator.key-value"], "sky"),
      tok(["keyword.control.directive", "punctuation.definition.directive", "meta.preprocessor", "entity.name.function.preprocessor"], "pink"),
      tok(["entity.name.function", "support.function", "meta.function-call.generic", "variable.function"], "blue"),
      tok(["support.function.builtin", "support.function.misc", "entity.name.function.macro"], "peach"),
      tok(["entity.name.type", "entity.name.class", "entity.other.inherited-class", "support.class", "support.type", "entity.name.type.class"], "yellow"),
      tok(["support.type.primitive", "support.type.builtin", "storage.type.primitive", "storage.type.built-in", "keyword.type"], "lavender"),
      tok(["entity.name.namespace", "entity.name.type.namespace", "entity.name.type.module", "storage.modifier.import", "storage.modifier.package"], "ochre", "italic"),
      tok(["variable", "variable.other", "variable.other.readwrite", "meta.definition.variable.name"], "text"),
      tok(["variable.parameter", "meta.parameter", "variable.parameter.function"], "maroon", "italic"),
      tok(["variable.language", "variable.language.this", "variable.language.self", "variable.language.super"], "red", "italic"),
      tok(["variable.other.property", "variable.other.object.property", "support.variable.property", "meta.object-literal.key", "entity.name.variable.field"], "lilac"),
      tok(["support.type.property-name", "support.type.property-name.json", "support.type.property-name.toml"], "blue"),
      tok(["support.type.property-name.css", "support.type.vendored.property-name.css"], "blue"),
      tok(["entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"], "yellow"),
      tok(["entity.name.tag.css", "entity.other.attribute-name.pseudo-class.css"], "lilac"),
      tok(["punctuation", "meta.brace", "punctuation.terminator", "punctuation.separator"], "overlay2"),
      tok(["entity.name.tag", "support.tag"], "blue"),
      tok(["entity.other.attribute-name"], "ochre", "italic"),
      tok(["punctuation.definition.tag"], "teal"),
      tok(["entity.name.label", "keyword.control.label"], "sapphire"),
      tok(["meta.decorator", "punctuation.decorator", "storage.type.annotation", "entity.name.function.decorator"], "peach"),
      tok(["invalid", "invalid.illegal"], "red"),
      tok(["invalid.deprecated"], "overlay1", "strikethrough"),
      tok(["markup.heading", "entity.name.section"], "blue", "bold"),
      tok(["markup.heading.1", "heading.1.markdown"], "red", "bold"),
      tok(["markup.heading.2", "heading.2.markdown"], "peach", "bold"),
      tok(["markup.heading.3", "heading.3.markdown"], "yellow", "bold"),
      tok(["markup.heading.4", "heading.4.markdown"], "green", "bold"),
      tok(["markup.heading.5", "heading.5.markdown"], "sapphire", "bold"),
      tok(["markup.heading.6", "heading.6.markdown"], "lilac", "bold"),
      tok(["markup.bold"], "maroon", "bold"),
      tok(["markup.italic"], "maroon", "italic"),
      tok(["markup.strikethrough"], "subtext0", "strikethrough"),
      tok(["markup.underline.link", "markup.underline.link.image", "string.other.link"], "blue", "underline"),
      tok(["markup.inline.raw", "markup.fenced_code", "markup.raw"], "green"),
      tok(["markup.quote"], "pink", "italic"),
      tok(["markup.list punctuation.definition.list.begin", "punctuation.definition.list.begin.markdown"], "teal"),
      tok(["markup.inserted", "meta.diff.header.to-file", "punctuation.definition.inserted"], "green"),
      tok(["markup.deleted", "meta.diff.header.from-file", "punctuation.definition.deleted"], "red"),
      tok(["markup.changed", "punctuation.definition.changed"], "blue"),
      tok(["meta.diff.range", "meta.diff.header"], "overlay1"),

      # Wider language coverage
      tok(["entity.name.function.member", "support.function.any-method", "meta.method-call entity.name.function", "variable.function"], "blue"),
      tok(["meta.function-call.generic", "meta.function-call.python"], "blue"),
      tok(["entity.name.function.constructor", "support.class.builtin"], "yellow"),
      tok(["entity.name.type.parameter", "storage.type.generic"], "maroon", "italic"),
      tok(["variable.parameter.function.language.special.self", "variable.language.special.self", "variable.language.special.cls"], "red", "italic"),
      tok(["support.constant", "constant.other.color", "keyword.other.unit", "constant.other.symbol"], "peach"),
      tok(["support.variable", "variable.other.predefined"], "red"),
      tok(["support.function.builtin.shell", "support.function.builtin.python"], "peach"),
      tok(["variable.other.normal.shell", "variable.other.positional.shell", "variable.other.special.shell"], "maroon"),
      tok(["punctuation.definition.variable.shell", "punctuation.definition.evaluation.backticks.shell"], "pink"),
      tok(["punctuation.section.embedded", "punctuation.definition.interpolation", "punctuation.definition.template-expression.begin", "punctuation.definition.template-expression.end"], "pink"),
      tok(["meta.embedded", "source.groovy.embedded", "meta.template.expression"], "text"),
      tok(["keyword.operator.assignment", "keyword.operator.arithmetic", "keyword.operator.comparison", "keyword.operator.relational", "storage.type.function.arrow"], "sky"),
      tok(["punctuation.definition.parameters", "punctuation.definition.arguments", "punctuation.section"], "overlay2"),
      tok(["entity.name.tag.yaml", "punctuation.support.type.property-name"], "blue"),
      tok(["string.unquoted.plain.out.yaml", "string.unquoted.yaml"], "green"),
      tok(["entity.name.section.group-title.ini", "entity.name.tag.table.toml"], "lavender", "bold"),
      tok(["punctuation.definition.heading.markdown", "punctuation.definition.bold.markdown", "punctuation.definition.italic.markdown"], "overlay2"),
      tok(["fenced_code.block.language", "markup.fenced_code.block.language"], "lilac", "italic"),
      tok(["markup.inline.raw.string.markdown"], "green"),
    ]

    semantic = {
      "enumMember": c["teal"], "selfKeyword": {"foreground": c["red"], "italic": True},
      "parameter": {"foreground": c["maroon"], "italic": True},
      "variable.defaultLibrary": c["red"], "variable.readonly.defaultLibrary": c["peach"],
      "property": c["lilac"], "property.readonly": c["lilac"],
      "function.defaultLibrary": c["peach"], "method.defaultLibrary": c["peach"],
      "namespace": {"foreground": c["ochre"], "italic": True},
      "type": c["yellow"], "class": c["yellow"], "interface": c["yellow"], "struct": c["yellow"],
      "enum": c["yellow"], "typeParameter": {"foreground": c["maroon"], "italic": True},
      "type.defaultLibrary": c["lavender"], "class.defaultLibrary": c["yellow"],
      "macro": c["pink"], "decorator": c["peach"], "builtinAttribute": c["peach"],
      "comment": {"foreground": c["overlay2"], "italic": True}, "label": c["sapphire"],
      "lifetime": {"foreground": c["red"], "italic": True},
    }

    theme = {
      "$schema": "vscode://schemas/color-theme",
      "name": c.name, "type": "dark",
      "semanticHighlighting": True,
      "colors": colors, "tokenColors": tokenColors, "semanticTokenColors": semantic,
    }
    return {OUT: json.dumps(theme, indent=2) + "\n"}
