"""Zen Browser userChrome.css (browser UI), userContent.css (about: pages) and
the user.js that makes Zen load them.

Zen reads these from <profile>/chrome/, and the profile folder name differs per
machine, so they are written to a folder per theme in the zen package and
linked into the profile by the "After stowing" step in zen/DEPENDENCIES.md.
The variable names follow catppuccin/zen-browser.
"""
from palette import blend

DIR = "zen/.config/zen/{slug}"

HEADER = """/* {name}, generated by theming/generate.py from {source}.
   Edit those, not this file. */
"""


def block(selector, props, indent="  "):
    body = "\n".join(f"{indent}  {k}: {v} !important;" for k, v in props.items())
    return f"{indent}{selector} {{\n{body}\n{indent}}}"


def identity_colors(c, indent):
    # Firefox container colors, in the names Firefox uses for them
    colors = {
        "blue": c.hue.blue, "turquoise": c.hue.teal, "green": c.hue.green, "yellow": c.hue.yellow,
        "orange": c.hue.orange, "red": c.hue.red, "pink": c.hue.pink, "purple": c.hue.purple,
    }
    return [
        block(f".identity-color-{name}",
              {"--identity-tab-color": color, "--identity-icon-color": color}, indent)
        for name, color in colors.items()
    ]


def user_chrome(c):
    accent = c.accent
    frame = c.base  # sidebar, tab strip and the border around pages
    rules = [
        block(":root", {
            "--zen-primary-color": accent,
            "--zen-colors-primary": c.surface0,
            "--zen-colors-secondary": c.surface0,
            "--zen-colors-tertiary": c.mantle,
            "--zen-colors-border": c.surface1,
            "--zen-themed-toolbar-bg": frame,
            "--zen-main-browser-background": frame,
            "--toolbox-bgcolor-inactive": frame,
            "--toolbar-bgcolor": c.surface0,
            "--toolbar-color": c.text,
            "--toolbar-field-color": c.text,
            "--toolbar-field-focus-color": c.text,
            "--toolbarbutton-icon-fill": c.subtext1,
            "--lwt-text-color": c.text,
            "--tab-selected-textcolor": c.bright,
            "--arrowpanel-background": c.base,
            "--arrowpanel-color": c.text,
            "--sidebar-text-color": c.text,
            "--lwt-sidebar-text-color": c.text,
            "--lwt-sidebar-background-color": frame,
            "--newtab-background-color": c.base,
            "--newtab-text-primary-color": c.text,
        }),
        # A workspace's theme-picker color is set inline on these two, and a light one flips
        # #browser to Zen's light scheme (dark text), so pin both to the palette instead
        block(":is(#zen-browser-background, #zen-toolbar-background)", {
            "--zen-main-browser-background": frame,
            "--zen-main-browser-background-old": frame,
            "--zen-main-browser-background-toolbar": frame,
            "--zen-main-browser-background-toolbar-old": frame,
            "--zen-grainy-background-opacity": "0",
        }),
        # zen-workspace is each workspace's part of the sidebar (tabs, folders, new tab button),
        # and Zen sets that workspace's own text color and scheme inline on it
        block(":is(:root, #browser, #navigator-toolbox, #TabsToolbar, #tabbrowser-tabs, zen-workspace)", {
            "color-scheme": "dark",
            "--toolbar-color-scheme": "dark",
            "--toolbox-textcolor": c.text,
            "--toolbar-color": c.text,
            "--tab-text-color-selected": c.bright,
            "--tab-selected-textcolor": c.bright,
            "--zen-primary-color": accent,
        }),
        # Tabs inherit their text color through the toolbars above, so set it on them directly
        # too in case one of those still carries the workspace color's dark text
        block(":is(#navigator-toolbox, #TabsToolbar, #tabbrowser-tabs, zen-workspace, .tabbrowser-tab)",
              {"color": c.text}),
        block(".tabbrowser-tab:is([selected], [multiselected]) .tab-content", {"color": c.bright}),
        block(":is(#TabsToolbar, hbox#titlebar, #zen-appcontent-navbar-container)",
              {"background-color": frame}),
        block(":is(.urlbar-background, .sidebar-placesTree, #zen-workspaces-button)",
              {"background-color": c.surface0}),
        block(".urlbarView-url", {"color": accent}),
        block(".content-shortcuts", {"background-color": c.base, "border-color": accent}),
        block("#zenEditBookmarkPanelFaviconContainer", {"background": c.crust}),
        block("#permissions-granted-icon", {"color": frame}),
        block("#zen-media-controls-toolbar #zen-media-progress-bar::-moz-range-track",
              {"background": c.surface0}),
        *identity_colors(c, "  "),
    ]
    return (HEADER.format(name=c.name, source=c.source) + "\n@media (prefers-color-scheme: dark) {\n"
            + "\n\n".join(rules) + "\n}\n")


def user_content(c):
    accent = c.accent
    hover = blend(accent, 0.8, c.bright)
    active = blend(accent, 0.6, c.bright)

    def doc(match, rules):
        return f"  @-moz-document {match} {{\n" + "\n\n".join(rules) + "\n  }"

    sections = [
        doc('url-prefix("about:")', [block(":root", {
            "background-color": c.base,
            "--in-content-page-background": c.base,
            "--in-content-page-color": c.text,
            "--color-accent-primary": accent,
            "--color-accent-primary-hover": hover,
            "--color-accent-primary-active": active,
        }, "    ")]),
        doc('url("about:newtab"), url("about:home")', [
            block(":root", {
                "--newtab-background-color": c.base,
                "--newtab-background-color-secondary": c.surface0,
                "--newtab-element-hover-color": c.surface0,
                "--newtab-text-primary-color": c.text,
                "--newtab-wordmark-color": c.text,
                "--newtab-primary-action-background": accent,
            }, "    "),
            block(".icon", {"color": accent}, "    "),
            block(".card-outer:is(:hover, :focus, .active):not(.placeholder) .card-title",
                  {"color": accent}, "    "),
            block(".top-site-outer .search-topsite", {"background-color": c.secondary}, "    "),
        ]),
        doc('url-prefix("about:preferences")', [
            block(":root", {
                "--zen-colors-primary": c.surface0,
                "--zen-colors-tertiary": c.mantle,
                "--zen-primary-color": accent,
                "--in-content-text-color": c.text,
                "--in-content-box-background": c.surface0,
                "--link-color": accent,
                "--link-color-hover": hover,
            }, "    "),
            block(":is(groupbox, moz-card)", {"background": c.base}, "    "),
            block(":is(button, groupbox menulist)",
                  {"background": c.surface0, "color": c.text}, "    "),
            block(".main-content", {"background-color": c.crust}, "    "),
            *identity_colors(c, "    "),
        ]),
        doc('url-prefix("about:addons")', [block(":root", {
            "--zen-dark-color-mix-base": c.mantle,
            "--background-color-box": c.base,
        }, "    ")]),
        doc('url-prefix("about:protections")', [
            block(":root", {
                "--zen-primary-color": c.base,
                "--social-color": accent,
                "--coockie-color": c.hue.cyan,  # sic, Firefox's spelling
                "--fingerprinter-color": c.hue.yellow,
                "--cryptominer-color": c.property,
                "--tracker-color": c.hue.green,
                "--in-content-primary-button-background": c.surface2,
                "--in-content-primary-button-background-hover": c.overlay0,
                "--in-content-primary-button-text-color": c.text,
                "--in-content-primary-button-text-color-hover": c.text,
            }, "    "),
            block(".card", {"background-color": c.surface0}, "    "),
        ]),
    ]
    return (HEADER.format(name=c.name, source=c.source) + "\n@media (prefers-color-scheme: dark) {\n"
            + "\n\n".join(sections) + "\n}\n")


def user_js(c):
    return (f"// Lets Zen load chrome/userChrome.css and chrome/userContent.css (the {c.name} theme)\n"
            'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\n')


def build(c):
    out = DIR.format(slug=c.slug)
    return {
        f"{out}/userChrome.css": user_chrome(c),
        f"{out}/userContent.css": user_content(c),
        f"{out}/user.js": user_js(c),
    }
