"""zsh: ~/.dircolors (LS_COLORS for ls, fd and completion menus) and an Oh My
Zsh prompt theme.

.zshrc loads ~/.dircolors before Oh My Zsh and selects the prompt with
ZSH_THEME="wisteria-dusk".

Both use 24-bit colors, so file types can use palette accents that the 16
ANSI colors don't have.
"""

DIRCOLORS_OUT = "zsh/.dircolors"
THEME_OUT = "zsh/.oh-my-zsh/custom/themes/wisteria-dusk.zsh-theme"

HEADER = """# {name}
# Generated by theming/generate.py from theming/palette.json.
# Edit those, not this file.
"""

# File extensions per palette color. Source code and plain text stay uncolored.
EXTENSIONS = {
    "peach": ["tar", "tgz", "gz", "xz", "zst", "bz2", "lz4", "zip", "7z", "rar", "deb", "rpm", "jar"],
    "pink": ["png", "jpg", "jpeg", "gif", "webp", "avif", "svg", "bmp", "ico", "tif", "tiff", "xcf", "kra"],
    "ochre": ["mp3", "flac", "ogg", "opus", "wav", "m4a", "mp4", "mkv", "webm", "mov", "avi"],
    "flamingo": ["pdf", "epub", "djvu", "doc", "docx", "odt", "xls", "xlsx", "ods", "ppt", "pptx", "odp"],
    "maroon": ["iso", "img", "qcow2", "vdi", "vmdk", "appimage"],
    "yellow": ["pem", "crt", "key", "pub", "gpg", "asc", "sig"],
    "overlay0": ["bak", "old", "orig", "tmp", "swp", "swo", "part", "log", "lock"],
}


def sgr(fg=None, bg=None, bold=False):
    """An SGR sequence body, e.g. 01;38;2;129;183;253."""
    def rgb(color):
        return ";".join(str(int(color[i:i + 2], 16)) for i in (1, 3, 5))
    parts = ["01"] if bold else []
    if fg:
        parts.append(f"38;2;{rgb(fg)}")
    if bg:
        parts.append(f"48;2;{rgb(bg)}")
    return ";".join(parts)


def dircolors(c):
    types = {
        "DIR": sgr(c.lavender, bold=True),
        "LINK": sgr(c.sky),
        "ORPHAN": sgr(c.red, bold=True),
        "MISSING": sgr(c.red, bold=True),
        "EXEC": sgr(c.green, bold=True),
        "FIFO": sgr(c.yellow),
        "SOCK": sgr(c.pink),
        "DOOR": sgr(c.pink),
        "BLK": sgr(c.ochre, bold=True),
        "CHR": sgr(c.ochre, bold=True),
        "SETUID": sgr(c.crust, c.red),
        "SETGID": sgr(c.crust, c.yellow),
        # Sticky and world-writable dirs: keep the dir color, flag it with a background
        # instead of GNU's default green fill
        "STICKY": sgr(c.lavender, c.surface1, bold=True),
        "OTHER_WRITABLE": sgr(c.lavender, c.surface1, bold=True),
        "STICKY_OTHER_WRITABLE": sgr(c.lavender, c.surface1, bold=True),
    }
    lines = [HEADER.format(name=c.name), "# File types"]
    lines += [f"{name} {code}" for name, code in types.items()]
    for color, exts in EXTENSIONS.items():
        lines += ["", f"# {color}"]
        lines += [f".{ext} {sgr(c[color])}" for ext in exts]
    return "\n".join(lines) + "\n"


def prompt_theme(c):
    def fg(color):
        return "%F{" + color + "}"

    # Arrow is mint after a successful command (the "you are here" marker), red after a
    # failed one; %1{...%} tells zsh it is one column wide
    return HEADER.format(name=c.name) + "\n".join([
        "",
        'PROMPT="%(?:' + fg(c.mint) + '%B%1{➜%}%b:' + fg(c.red) + '%B%1{➜%}%b)%f '
        + fg(c.lavender) + '%B%c%b%f"',
        "PROMPT+=' $(git_prompt_info)'",
        "",
        f'ZSH_THEME_GIT_PROMPT_PREFIX="{fg(c.overlay2)}%1{{%}} "',
        'ZSH_THEME_GIT_PROMPT_SUFFIX="%f "',
        f'ZSH_THEME_GIT_PROMPT_DIRTY=" {fg(c.peach)}%1{{✗%}}"',
        'ZSH_THEME_GIT_PROMPT_CLEAN=""',
    ]) + "\n"


def build(c):
    return {
        DIRCOLORS_OUT: dircolors(c),
        THEME_OUT: prompt_theme(c),
    }
